const SCRIPT_URL="https://script.google.com/macros/s/AKfycbwxJkynCbAnts5Qhjg4hhDIlpd9lVTHZMm5UrAty5bXa6l6QIBwbBJ1HZWXmDHvHYz6/exec";
let maquinas=[],checklist=[],operador,maquina,tipo,tipoMaquina,ctx;
function mostrarLoading(e){document.getElementById("loading").style.display=e?"block":"none"}
function carregarTiposMaquina(){mostrarLoading(!0);const e=document.createElement("script"),t="callbackMaquinas";window[t]=function(e){maquinas=e;const t=[...new Set(e.map(e=>e.tipo))],a=document.getElementById("tipoMaquina");a.innerHTML="<option value=''>Selecione o tipo de máquina</option>",t.forEach(e=>{const t=document.createElement("option");t.value=e,t.text=e,a.add(t)}),mostrarLoading(!1)},e.src=`${SCRIPT_URL}?action=listarMaquinas&callback=${t}`,document.body.appendChild(e)}
function carregarMaquinas(){tipoMaquina=document.getElementById("tipoMaquina").value;const e=document.getElementById("maquina");e.innerHTML="<option value=''>Selecione a máquina</option>";maquinas.filter(e=>e.tipo===tipoMaquina).forEach(t=>{const a=document.createElement("option");a.value=t.nome,a.text=`${t.nome} (${t.placa})`,e.add(a)})}
function iniciarChecklist(){if(operador=document.getElementById("operador").value,maquina=document.getElementById("maquina").value,tipo=document.getElementById("tipo").value,tipoMaquina=document.getElementById("tipoMaquina").value,!operador||!maquina||!tipoMaquina)return Swal.fire("Preencha todos os campos!");carregarChecklist()}
function carregarChecklist(){mostrarLoading(!0);const e=document.createElement("script"),t="callbackChecklist";window[t]=function(e){checklist=e,montarChecklist(),mostrarLoading(!1)},e.src=`${SCRIPT_URL}?tipo=${encodeURIComponent(tipoMaquina)}&callback=${t}`,document.body.appendChild(e)}
function montarChecklist(){document.getElementById("login").style.display="none",document.getElementById("checklist").style.display="block",document.getElementById("tituloChecklist").innerText=`Checklist de ${tipo} - ${maquina}`;const e=document.getElementById("itensContainer");e.innerHTML="";let t="";checklist.forEach(a=>{a.categoria!==t&&(t=a.categoria,(()=>{const t=document.createElement("h3");t.innerText=a.categoria,e.appendChild(t)})());const n=document.createElement("div");n.className="item",n.innerHTML=`<p>${a.item}</p><label><input type='radio' name='${a.item}' value='OK'> OK</label><label><input type='radio' name='${a.item}' value='Não Conforme'> N/C</label><br><textarea placeholder='Observações' id='obs_${a.item}'></textarea>`,e.appendChild(n)});const a=document.getElementById("assinatura");ctx=a.getContext("2d");let n=!1;a.addEventListener("mousedown",e=>{n=!0,ctx.beginPath(),ctx.moveTo(e.offsetX,e.offsetY)}),a.addEventListener("mousemove",e=>{n&&(ctx.lineTo(e.offsetX,e.offsetY),ctx.stroke())}),a.addEventListener("mouseup",()=>n=!1)}
function limparAssinatura(){const e=document.getElementById("assinatura");ctx.clearRect(0,0,e.width,e.height)}
function voltarInicio(){document.getElementById("checklist").style.display="none",document.getElementById("login").style.display="block"}
async function enviar(){const e=[];checklist.forEach(t=>{const a=document.querySelector(`input[name='${t.item}']:checked`)?.value||"",n=document.getElementById(`obs_${t.item}`).value;e.push({nome:t.item,status:a,observacao:n})});const t=document.getElementById("assinatura").toDataURL(),a={operador,maquina,tipo,assinatura:t,items:e},n=await Swal.fire({title:"Confirmar envio?",text:"Deseja enviar o checklist agora?",icon:"question",showCancelButton:!0,confirmButtonText:"Sim, enviar",cancelButtonText:"Cancelar"});if(!n.isConfirmed)return;mostrarLoading(!0);const o=await fetch(SCRIPT_URL,{method:"POST",body:JSON.stringify(a)});mostrarLoading(!1),o.ok?Swal.fire("Sucesso","Checklist enviado com sucesso!","success"):Swal.fire("Erro","Falha ao enviar checklist.","error")}
window.onload=carregarTiposMaquina;